capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 281,365,1233,1610
- action: key
  value: right
- action: delay
  value: '300'
- action: click
  value: 820,1220
- action: delay
  value: '500'
max_page: 1500
monitor: 1
pre_macro:
- action: capture
  value: asdf
- action: click
  value: 820,1220
same_count: 3
