capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 162,236,1464,1444
- action: key
  value: right
- action: delay
  value: '500'
max_page: 1500
monitor: 0
pre_macro:
- action: click
  value: 910,619,235,258
same_count: 3
