capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 814,223,928,916
- action: key
  value: right
- action: click
  value: 1408,1081,149,25
- action: delay
  value: '500'
max_page: 1500
monitor: 0
pre_macro:
- action: capture
  value: 820,271,360,850
- action: click
  value: 1255,467,198,139
same_count: 3
