capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 312,154,1266,1825
- action: scroll
  value: 673,616,645,451
- action: delay
  value: '1200'
max_page: 1500
monitor: 0
pre_macro: []
same_count: 3
