capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 1810,456,769,1143
- action: key
  value: right
- action: click
  value: 2113,1624,222,40
- action: delay
  value: '500'
max_page: 1500
monitor: 0
pre_macro:
- action: capture
  value: 1240,430,523,559
- action: capture
  value: 0,0,6484,3258
same_count: 3
