capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 1251,466,574,649
- action: key
  value: right
- action: click
  value: 2035,1273,339,178
- action: delay
  value: '500'
max_page: 1500
monitor: 0
pre_macro:
- action: capture
  value: 546,951,660,873
- action: capture
  value: 0,0,3840,2157
same_count: 3
