capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 1368,399,550,631
- action: key
  value: right
- action: delay
  value: '500'
max_page: 1500
monitor: 0
pre_macro:
- action: click
  value: 2089,643,124,118
same_count: 3
