capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 444,667,437,661
- action: delay
  value: right
- action: delay
  value: '3000'
- action: click
  value: 820,1220
- action: delay
  value: '500'
max_page: 1500
monitor: 0
pre_macro:
- action: capture
  value: 329,560,666,948
- action: click
  value: 820,1220
same_count: 3
