capture_path: ./capture
image_quality: 88
macro:
- action: capture
  value: 1251,466,574,649
- action: key
  value: right
- action: delay
  value: '300'
max_page: 1500
monitor: 0
pre_macro:
- action: click
  value: 910,619,235,258
same_count: 3
